global:
  registry: docker.io
  useDigest: false
  capiOnboardAnnotation: ""
  imagePullSecrets: []
    # - name: my-registry-secret
  additionalLabels: {}
  enableNatsWatcher: false
accessManager:
  enabled: true
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/access-manager
      tag: v1.7.0
      digest: sha256:287997687026316a126c540f514b0d5f7e0820ac9dcac9290613b230594e9754
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
addonController:
  annotations: {}
  labels: {}
  initialization:
    image:
      repository: projectsveltos/addon-controller
      tag: v1.7.0
      digest: sha256:eba2d3408b93db1d37f1ecae5238254c911cf1fac3a564ea49a0b505695f27a2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  controller:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.7.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.7.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: projectsveltos/addon-controller
      tag: v1.7.0
      digest: sha256:eba2d3408b93db1d37f1ecae5238254c911cf1fac3a564ea49a0b505695f27a2
    resources:
      requests:
        memory: 512Mi
  driftDetectionManagerPatchConfigMap:
    name: drift-detection-config
    data: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  nodeSelector: {}
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
  roleExtra:
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - create
          - update
  clusterRoleExtra:
    rules: null
classifierManager:
  annotations: {}
  labels: {}
  agentPatchConfigMap:
    name: sveltos-agent-config
    data: {}
  agentPatchSveltosApplierConfigMap:
    name: sveltos-applier-config
    data: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.7.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.7.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/classifier
      tag: v1.7.0
      digest: sha256:eaaf95d84f75699cd727f6a0b206d5ca5d4ce5a5da844bfd1886d524acbd9261
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
driftDetectionManager:
  serviceAccount:
    annotations: {}
eventManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.7.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.7.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/event-manager
      tag: v1.7.0
      digest: sha256:6d8a13773841e008f5aea7dcb468a774a400b1e8c25e6a98c6576b46334d9127
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
hcManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.7.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.7.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/healthcheck-manager
      tag: v1.7.0
      digest: sha256:33891e8c2edb6dfc50fcc8b7396cb1672c2e9cd67666a52bc0b56e0dc18f7b43
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
crdManager:
  serviceAccount:
    annotations:
      helm.sh/hook: pre-upgrade,pre-rollback
      helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
crdManagerJob:
  backoffLimit: 4
  crdManager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/crd-manager
      tag: v1.7.0
      digest: sha256:df724b71febb7218a3cee1dead4600b360f480c71816981b2dfb626ed205b86e
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        memory: 128Mi
kubernetesClusterDomain: cluster.local
registerMgmtCluster:
  serviceAccount:
    annotations: {}
registerMgmtClusterJob:
  backoffLimit: 4
  registerMgmtCluster:
    args:
      - --labels=
      - --service-account-token=false
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/register-mgmt-cluster
      tag: v1.7.0
      digest: sha256:072ec92cf5cb09e32fd2e0718fd28098514a6bbdb92a0461c53998a218419514
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        memory: 128Mi
scManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/sveltoscluster-manager
      tag: v1.7.0
      digest: sha256:d4ed6f926bc9954fc7175d643df431e78de34384cb19c2300270903f0ddfaa04
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
shardController:
  enabled: true
  annotations: {}
  labels: {}
  extraEnv: []
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
      - --report-mode=0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --agent-in-mgmt-cluster=true
      - --v=5
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/shard-controller
      tag: v1.7.0
      digest: sha256:e27b3973f488296b6f6e3931463d0b8081bb392e77934a431d12c2e17b4b0f54
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
techsupportController:
  enabled: true
  annotations: {}
  labels: {}
  extraEnv: []
  controller:
    args:
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/techsupport
      tag: v1.7.0
      digest: sha256:c23c546c0d210e9aa8580f790523b8c0f55c9e62871f9d56a63ff69f06b1e24f
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  tolerations: []
  serviceAccount:
    annotations: {}
mcpServer:
  enabled: true
  annotations: {}
  labels: {}
  controller:
    args:
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/mcp-server
      tag: v1.7.0
      digest: sha256:3e208bef095920194f22431f382eeafa6a9c42ed8cb5018b3da186a7cf837992
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8080
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
sveltosAgentManager:
  serviceAccount:
    annotations: {}
prometheus:
  enabled: false
agent:
  managementCluster: false
telemetry:
  disabled: false
defaultClassifier:
  annotations: {}
  labels: {}
defaultDebuggingConfiguration:
  annotations: {}
  labels: {}
