global:
  registry: docker.io
  useDigest: false
  capiOnboardAnnotation: ""
  imagePullSecrets: []
    # - name: my-registry-secret
  additionalLabels: {}
  enableNatsWatcher: false
accessManager:
  enabled: true
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
    extraArgs: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/access-manager
      tag: v1.10.0
      digest: sha256:27704c35c5b4a5ab48e8047c4a40eb731aa3799f9c197e8bd6319c8cdca92333
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
addonController:
  annotations: {}
  labels: {}
  initialization:
    image:
      repository: projectsveltos/addon-controller
      tag: v1.10.0
      digest: sha256:71e391b8d3f72185462037c13d112e677cf3f61c9e6dc305e61681eba2e88932
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  controller:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.10.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.10.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: projectsveltos/addon-controller
      tag: v1.10.0
      digest: sha256:71e391b8d3f72185462037c13d112e677cf3f61c9e6dc305e61681eba2e88932
    resources:
      requests:
        memory: 512Mi
  driftDetectionManagerPatchConfigMap:
    name: drift-detection-config
    data: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  nodeSelector: {}
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
  roleExtra:
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - create
          - update
  clusterRoleExtra:
    rules: null
  serviceMonitor:
    additionalLabels: {}
classifierManager:
  annotations: {}
  labels: {}
  agentPatchConfigMap:
    name: sveltos-agent-config
    data: {}
  agentPatchSveltosApplierConfigMap:
    name: sveltos-applier-config
    data: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.10.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.10.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/classifier
      tag: v1.10.0
      digest: sha256:b690a710e847fad71ab573cdea8872cc1488512f6ca2f375a036e0a33335c0b0
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
driftDetectionManager:
  serviceAccount:
    annotations: {}
eventManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.10.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.10.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/event-manager
      tag: v1.10.0
      digest: sha256:772763ae15f0935971fbf0614e21c1800ab89966b77dea6c84dde90778815455
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
hcManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.10.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.10.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/healthcheck-manager
      tag: v1.10.0
      digest: sha256:2125ccce8c407ca3a4b98677acc5f856a26606366a3355a6815df05d9c20d4aa
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
crdManager:
  serviceAccount:
    annotations:
      helm.sh/hook: pre-upgrade,pre-rollback
      helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
crdManagerJob:
  backoffLimit: 4
  crdManager:
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/crd-manager
      tag: v1.10.0
      digest: sha256:2076e711fdfa9dd420f75417c854be20c932508f7449728777e2601773d84ac4
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        memory: 128Mi
kubernetesClusterDomain: cluster.local
registerMgmtCluster:
  serviceAccount:
    annotations: {}
registerMgmtClusterJob:
  backoffLimit: 4
  registerMgmtCluster:
    args:
      - --labels=
      - --service-account-token=false
    extraArgs: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/register-mgmt-cluster
      tag: v1.10.0
      digest: sha256:f86198745ff82334ea5d3b79a2f42b609f8e0d780f01cae53d99c3f0bb3a3d80
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        memory: 128Mi
scManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
    extraArgs: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/sveltoscluster-manager
      tag: v1.10.0
      digest: sha256:1588a7e106f34d7f5238c38786c7260f46319297a43d942bc9b0ea6aaeffa0b6
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
  serviceMonitor:
    additionalLabels: {}
shardController:
  enabled: true
  annotations: {}
  labels: {}
  extraEnv: []
  extraVolumes: []
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
      - --report-mode=0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --agent-in-mgmt-cluster=true
      - --v=5
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/shard-controller
      tag: v1.10.0
      digest: sha256:c08074b942dfa0441e2c2f7b9b2c3139d2a35c00258661b6f55dbba5f5686032
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
techsupportController:
  enabled: true
  annotations: {}
  labels: {}
  extraEnv: []
  extraVolumes: []
  controller:
    args:
      - --v=5
    extraArgs: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/techsupport
      tag: v1.10.0
      digest: sha256:17a318588942ea2575a49972f75a877a19f765208943340e97a3610898b2f09a
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  tolerations: []
  serviceAccount:
    annotations: {}
mcpServer:
  enabled: true
  annotations: {}
  labels: {}
  controller:
    args:
      - --v=5
    extraArgs: {}
    extraEnv: []
    extraVolumes: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/mcp-server
      tag: v1.10.0
      digest: sha256:41acddae75856d49af40cc996d568db92d1cf570f963f3f147d93d12bf08b12b
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8080
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
sveltosAgentManager:
  serviceAccount:
    annotations: {}
prometheus:
  enabled: false
agent:
  managementCluster: false
telemetry:
  disabled: false
defaultClassifier:
  annotations: {}
  labels: {}
defaultDebuggingConfiguration:
  annotations: {}
  labels: {}
