global:
  registry: docker.io
  useDigest: false
  capiOnboardAnnotation: ""
  imagePullSecrets: []
    # - name: my-registry-secret
  additionalLabels: {}
accessManager:
  enabled: true
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/access-manager
      tag: v1.6.0
      digest: sha256:006dda70aa7ba9b058a41cd0a94d99daf482cfaaa1e6633efe8d0cd1bbad48bc
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
addonController:
  annotations: {}
  labels: {}
  initialization:
    image:
      repository: projectsveltos/addon-controller
      tag: v1.6.0
      digest: sha256:70c85f85f2bcff1349d89ef12f9f725764139ec524620821cb85410597ff8e92
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  controller:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.6.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.6.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: projectsveltos/addon-controller
      tag: v1.6.0
      digest: sha256:70c85f85f2bcff1349d89ef12f9f725764139ec524620821cb85410597ff8e92
    resources:
      requests:
        memory: 512Mi
  driftDetectionManagerPatchConfigMap:
    name: drift-detection-config
    data: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  nodeSelector: {}
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
  roleExtra:
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - create
          - update
  clusterRoleExtra:
    rules: null
classifierManager:
  annotations: {}
  labels: {}
  agentPatchConfigMap:
    name: sveltos-agent-config
    data: {}
  agentPatchSveltosApplierConfigMap:
    name: sveltos-applier-config
    data: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.6.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v1.6.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/classifier
      tag: v1.6.0
      digest: sha256:004ea02cf4868a1ab4ff5bacb88b265306e01343900421216a760f7688ce51ea
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
driftDetectionManager:
  serviceAccount:
    annotations: {}
eventManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.6.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.6.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/event-manager
      tag: v1.6.0
      digest: sha256:e2443f935e519329b70106668b0c82819b9c343f48199bacb96e267db164bfe8
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
hcManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.6.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v1.6.0
      - --agent-in-mgmt-cluster=true
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/healthcheck-manager
      tag: v1.6.0
      digest: sha256:2bdb773bbe1282ce8fc551e118f9f65dbe9edef73414b2ba25af0747bfbb6c56
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
crdManager:
  serviceAccount:
    annotations:
      helm.sh/hook: pre-upgrade,pre-rollback
      helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
crdManagerJob:
  backoffLimit: 4
  crdManager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/crd-manager
      tag: v1.6.0
      digest: sha256:3ec515e46b17ba6df9c393072f94c07758e4fa6ca261058e905754dc172a379f
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        memory: 128Mi
kubernetesClusterDomain: cluster.local
registerMgmtCluster:
  serviceAccount:
    annotations: {}
registerMgmtClusterJob:
  backoffLimit: 4
  registerMgmtCluster:
    args:
      - --labels=
      - --service-account-token=false
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/register-mgmt-cluster
      tag: v1.6.0
      digest: sha256:30600f61c90fa9115c07143f4adaddfff1c5411718480bff201fb449307e3721
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        memory: 128Mi
scManager:
  annotations: {}
  labels: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/sveltoscluster-manager
      tag: v1.6.0
      digest: sha256:39edd0b0e4715d53d00eefb8f50c906d81d9ea021ba198cdceea57c53132bc52
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
shardController:
  enabled: true
  annotations: {}
  labels: {}
  extraEnv: []
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
      - --report-mode=0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --agent-in-mgmt-cluster=true
      - --v=5
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/shard-controller
      tag: v1.6.0
      digest: sha256:1403c80aa011311a411ca8d8448c4edca564a5d3ca230dd5b0d6cd067df9a024
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  serviceAccount:
    annotations: {}
techsupportController:
  enabled: true
  annotations: {}
  labels: {}
  extraEnv: []
  controller:
    args:
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/techsupport
      tag: v1.6.0
      digest: sha256:bd95f1bd98875fc3f8ee700dac502d52e0ae751758854285aef3ae134b02fb5d
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  tolerations: []
  serviceAccount:
    annotations: {}
mcpServer:
  enabled: true
  annotations: {}
  labels: {}
  controller:
    args:
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: projectsveltos/mcp-server
      tag: v1.6.0
      digest: sha256:f879e682bf8f26a32ca785e3b1a0ec8f93fb7bcccc1f0e8c57c9781ce2d021ac
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8080
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
sveltosAgentManager:
  serviceAccount:
    annotations: {}
prometheus:
  enabled: false
agent:
  managementCluster: false
telemetry:
  disabled: false
defaultClassifier:
  annotations: {}
  labels: {}
defaultDebuggingConfiguration:
  annotations: {}
  labels: {}
