apiVersion: v1
kind: Service
metadata:
  name: addon-controller
  namespace: {{ .Release.Namespace | quote }}
  labels:
    control-plane: addon-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.addonController.type }}
  selector:
    control-plane: addon-controller
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.addonController.ports | toYaml | nindent 2 -}}
{{ if .Values.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: addon-controller
  namespace: {{ .Release.Namespace | quote }}
  labels:
    control-plane: addon-controller
  {{- with .Values.addonController.serviceMonitor.additionalLabels -}}
    {{- toYaml . | nindent 4 -}}
  {{- end -}}
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: https
    {{- with .Values.prometheus.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- include "projectsveltos.serviceMonitorAuth" . | nindent 4 }}
  namespaceSelector:
    matchNames:
    - '{{ .Release.Namespace }}'
  selector:
    matchLabels:
      control-plane: addon-controller
{{ end }}
