apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-controller-role-extra
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
{{- if .Values.addonController.roleExtra.rules }}
rules:
{{- toYaml .Values.addonController.roleExtra.rules | nindent 0 }}
{{- else }}
rules: null
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-controller-role-extra
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
{{- if .Values.addonController.clusterRoleExtra.rules }}
rules:
{{- toYaml .Values.addonController.clusterRoleExtra.rules | nindent 0 }}
{{- else }}
rules: null
{{- end }}